const designs = [
  {
    id: 1,
    imageUrl: 'src/assets/image/Template1 (1).png',
    title: 'Maulana Creative',
    author: 'Mokhrom Blackletter',
    likes: 29,
    views: '7.5k',
    color: 'red',
    colorHex: '#ff0000',  // Color hex code
    tags: ['branding', 'print'],
    createdDate: '2024-06-01',
    popular: true,
    Following:true,
    new:true,
    description: 'This design showcases a modern and sleek branding concept with vibrant colors.',
  },
  {
    id: 2,
    imageUrl: 'src/assets/image/Template1 (2).png',
    title: 'Maulana Creative',
    author: 'Killae Serif Aesthetic',
    likes: 306,
    views: '32.2k',
    color: 'saddlebrown',
    colorHex: '#8b4513',  // Color hex code
    tags: ['web-design', 'product-design'],
    createdDate: '2024-06-15',
    popular: true,
    Following:true,
    new:true,
    description: 'Aesthetic and functional web design with a focus on user experience and visual appeal.',
  },
  {
    id: 3,
    imageUrl: 'src/assets/image/Template1 (3).png',
    title: 'Caraka',
    author: 'Plant Solid Icons',
    likes: 105,
    views: '13.4k',
    color: 'blue',
    colorHex: '#0000ff',  // Color hex code
    tags: ['illustration', 'mobile'],
    createdDate: '2024-05-20',
    popular: true,
    Following:true,
    new:true,
    description: 'Detailed and artistic illustration suitable for mobile applications.',
  },
  {
    id: 4,
    imageUrl: 'src/assets/image/Template1 (4).png',
    title: 'Wix Studio',
    author: 'Nasir Studio built on Wix Studio',
    likes: 217,
    views: '18.5k',
    color: 'black',
    colorHex: '#000000',  // Color hex code
    tags: ['typography', 'animation'],
    createdDate: '2024-06-10',
    popular: true,
    Following:true,
    new:true,
    description: 'Typography-focused design with dynamic animations, built using Wix Studio.',
  },
  {
    id: 5,
    imageUrl: 'src/assets/image/Template5.png',
    title: 'Matthew Jedrzejewski',
    author: 'Arcane',
    likes: 703,
    views: '213k',
    color: 'brown',
    colorHex: '#a52a2a',  // Color hex code
    tags: ['branding', 'web-design'],
    createdDate: '2024-06-20',
    popular: true,
    Following:true,
    new:true,
    description: 'Bold branding and web design approach with a focus on attracting attention.',
  },
  {
    id: 6,
    imageUrl: 'src/assets/image/Template6.png',
    title: 'Alex Tkachev',
    author: 'Serenita',
    likes: 351,
    views: '91.8k',
    color: 'white',
    colorHex: '#ffffff',  // Color hex code
    tags: ['print', 'product-design'],
    createdDate: '2024-05-25',
    popular: true,
    Following:true,
    new:true,
    description: 'Clean and minimalist print and product design that emphasizes simplicity.',
  },
  {
    id: 7,
    imageUrl: 'src/assets/image/Template7.png',
    title: 'LoganCee Studio',
    author: 'Team',
    likes: 136,
    views: '18.2k',
    color: 'black',
    colorHex: '#000000',  // Color hex code
    tags: ['illustration', 'animation'],
    createdDate: '2024-06-05',
    popular: true,
    Following:true,
    new:true,
    description: 'Creative and animated illustrations designed by a collaborative team.',
  },
  {
    id: 8,
    imageUrl: 'src/assets/image/Template8.png',
    title: 'Yuhang',
    author: 'Smart Stack Concepts 3',
    likes: 110,
    views: '9.7k',
    color: 'navy',
    colorHex: '#000080',  // Color hex code
    tags: ['typography', 'mobile'],
    createdDate: '2024-06-18',
    popular: true,
    Following:true,
    new:true,
    description: 'Typography-focused mobile design with innovative stacking concepts.',
  },
  {
    id: 9,
    imageUrl: 'src/assets/image/Template9.png',
    title: 'Amy Nortman Holocomb',
    author: 'Stellar Bank',
    likes: 30,
    views: '21',
    color: 'navy',
    colorHex: '#a52a2a',  // Color hex code
    tags: ['branding', 'web-design'],
    createdDate: '2024-06-20',
    popular: true,
    Following:true,
    new:true,
    description: 'High-impact branding and web design for financial institutions.',
  },
  {
    id: 10,
    imageUrl: 'src/assets/image/Template10.png',
    title: 'Maulana Creative',
    author: 'Halqueen Display',
    likes: 51,
    views: '45',
    color: 'red',
    colorHex: '#000000',  // Color hex code
    tags: ['print', 'product-design'],
    createdDate: '2024-05-25',
    popular: true,
    Following:true,
    new:true,
    description: 'Creative print and product design with a focus on unique display techniques.',
  },
  {
    id: 11,
    imageUrl: 'src/assets/image/Template11.png',
    title: 'Vernoica Grytsenko',
    author: 'Flamiest Horror Display',
    likes: 16,
    views: '182',
    color: 'blue',
    colorHex: '#ffffff',  // Color hex code
    tags: ['illustration', 'animation'],
    createdDate: '2024-06-05',
    popular: true,
    Following:true,
    new:true,
    description: 'Intense and vibrant illustration with horror-themed animations.',
  },
  {
    id: 12,
    imageUrl: 'src/assets/image/Template12.png',
    title: 'Alex Tkachev',
    author: 'Eiclare Decorative',
    likes: 11,
    views: '90',
    color: 'green',
    colorHex: '#000080',  // Color hex code
    tags: ['typography', 'mobile'],
    createdDate: '2024-06-18',
    popular: true,
    Following:true,
    new:true,
    description: 'Decorative typography design suitable for mobile applications.',
  },
  {
    id: 13,
    imageUrl: 'src/assets/image/Template13.png',
    title: 'Bre Mccallum',
    author: 'Apple Pattern',
    likes: 70,
    views: '280',
    color: 'orange',
    colorHex: '#a52a2a',  // Color hex code
    tags: ['branding', 'web-design'],
    createdDate: '2024-06-20',
    popular: true,
    Following:true,
    new:true,
    description: 'Fruit-inspired branding and web design with a fresh and lively pattern.',
  },
  {
    id: 14,
    imageUrl: 'src/assets/image/Template14.png',
    title: 'Bre Mccallum',
    author: 'Murchiz Blackletter',
    likes: 35,
    views: '64',
    color: 'black',
    colorHex: '#000000',  // Color hex code
    tags: ['print', 'product-design'],
    createdDate: '2024-05-25',
    popular: true,
    Following:true,
    new:true,
    description: 'Blackletter-inspired print and product design with a modern twist.',
  },
  {
    id: 15,
    imageUrl: 'src/assets/image/Template15.png',
    title: 'Deena Dhayalan',
    author: 'Cilibazz Graffiti Display',
    likes: 13,
    views: '65',
    color: 'green',
    colorHex: '#ffffff',  // Color hex code
    tags: ['illustration', 'animation'],
    createdDate: '2024-06-05',
    popular: true,
    Following:true,
    new:true,
    description: 'Colorful and expressive graffiti-style illustration with dynamic animations.',
  },
  {
    id: 16,
    imageUrl: 'src/assets/image/Template16.png',
    title: 'Aiarty Image Enhancer',
    author: 'Borque Display Font',
    likes: 20,
    views: '230',
    color: 'violet',
    colorHex: '#000080',  // Color hex code
    tags: ['typography', 'mobile'],
    createdDate: '2024-06-18',
    popular: true,
    Following:true,
    new:true,
    description: 'Enhanced typography design with a focus on legibility and visual impact',
  },
];
export default designs;